### ISSUE TITLE
install hw without designware problem?

### ISSUE THREAD

**Issue by chifredhong** [nvdla/hw#177] opened 2018-07-16 08:23 UTC
I want to launch  the  sanity  test(nvdla_full) , so I input the command `./tools/bin/tmake -build verif_sim`  according the guide. part of my output log  is here. Should I need to Install VCS ？

==============================================
files are generated under /home/chifred/NVDLA/nvdlav1/hw/outdir/nv_full/vmod/nvdla/top
==============================================
make: Leaving directory '/home/chifred/NVDLA/nvdlav1/hw/vmod/nvdla/top'
make: Entering directory '/home/chifred/NVDLA/nvdlav1/hw/verif/sim'
DUTDIR = dut
VIPDIR = vip
Using cleartext directories
/home/tools/vcs/mx-2015.09-SP2-9-T0426/bin/vcs -f /home/chifred/NVDLA/nvdlav1/hw/verif/dut/dut.f  -Xddg=0x1 -o ./simv -cpp /home/utils/gcc-4.7.2/bin/g++  +nospecify +notimingchecks +define+VLIB_NO_UDP +warn=noTFIPC +warn=noTMR -full64 -y /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb -y /home/chifred/NVDLA/nvdlav1/hw/verif/../outdir/nv_full/vmod/vlibs +incdir+/home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb +incdir+/home/chifred/NVDLA/nvdlav1/hw/verif/dut +incdir+/home/chifred/NVDLA/nvdlav1/hw/verif/../outdir/nv_full/vmod/vlibs +incdir+/home/chifred/NVDLA/nvdlav1/hw/verif/../outdir/nv_full/vmod/include +incdir+/home/chifred/NVDLA/nvdlav1/hw/verif/../outdir/nv_full/vmod/vlibs +incdir+..  +define+DESIGNWARE_NOEXIST +vcs+lic+wait -sverilog +libext+.v +libext+.sv -timescale=1ns/1ns -debug_all +define+NVTOOLS_SYNC2D_GENERIC_CELL +define+NO_PERFMON_HISTOGRAM +define+PRAND_OFF  +define+NO_DUMPS /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/tb_top.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/csb_master.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/csb_master_seq.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/axi_slave.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/id_fifo.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/memory.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/memresp_fifo.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/raddr_fifo.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/slave_mem_wrap.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/waddr_fifo.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/wdata_fifo.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/wstrb_fifo.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/clk_divider.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/slave2mem_rd.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/slave2mem_wr.v /home/chifred/NVDLA/nvdlav1/hw/verif/../outdir/nv_full/vmod/vlibs/NV_DW02_tree.v /home/chifred/NVDLA/nvdlav1/hw/verif/../outdir/nv_full/vmod/vlibs/NV_DW_lsd.v /home/chifred/NVDLA/nvdlav1/hw/verif/../outdir/nv_full/vmod/vlibs/NV_DW_minmax.v -l ./simv.compile.log    -Mdir=./simvCsrc ; ./checkcompile.pl ./simv.compile.log ./simv
/bin/sh: 1: /home/tools/vcs/mx-2015.09-SP2-9-T0426/bin/vcs: not found

checkcompile : Compile FAILED (Warnings=0, Errors=0, ExecutableReady=0) 
The executable (./simv) has been removed.

/home/tools/vcs/mx-2015.09-SP2-9-T0426/bin/vcs -f /home/chifred/NVDLA/nvdlav1/hw/verif/dut/dut.f  -Xddg=0x1 -o ./simv -cpp /home/utils/gcc-4.7.2/bin/g++  +nospecify +notimingchecks +define+VLIB_NO_UDP +warn=noTFIPC +warn=noTMR -full64 -y /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb -y /home/chifred/NVDLA/nvdlav1/hw/verif/../outdir/nv_full/vmod/vlibs +incdir+/home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb +incdir+/home/chifred/NVDLA/nvdlav1/hw/verif/dut +incdir+/home/chifred/NVDLA/nvdlav1/hw/verif/../outdir/nv_full/vmod/vlibs +incdir+/home/chifred/NVDLA/nvdlav1/hw/verif/../outdir/nv_full/vmod/include +incdir+/home/chifred/NVDLA/nvdlav1/hw/verif/../outdir/nv_full/vmod/vlibs +incdir+..  +define+DESIGNWARE_NOEXIST +vcs+lic+wait -sverilog +libext+.v +libext+.sv -timescale=1ns/1ns -debug_all +define+NVTOOLS_SYNC2D_GENERIC_CELL +define+NO_PERFMON_HISTOGRAM +define+PRAND_OFF  +define+NO_DUMPS /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/tb_top.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/csb_master.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/csb_master_seq.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/axi_slave.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/id_fifo.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/memory.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/memresp_fifo.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/raddr_fifo.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/slave_mem_wrap.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/waddr_fifo.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/wdata_fifo.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/wstrb_fifo.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/clk_divider.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/slave2mem_rd.v /home/chifred/NVDLA/nvdlav1/hw/verif/synth_tb/slave2mem_wr.v /home/chifred/NVDLA/nvdlav1/hw/verif/../outdir/nv_full/vmod/vlibs/NV_DW02_tree.v /home/chifred/NVDLA/nvdlav1/hw/verif/../outdir/nv_full/vmod/vlibs/NV_DW_lsd.v /home/chifred/NVDLA/nvdlav1/hw/verif/../outdir/nv_full/vmod/vlibs/NV_DW_minmax.v -l ./simv.compile.log   
make: /home/tools/vcs/mx-2015.09-SP2-9-T0426/bin/vcs：命令未找到
make: *** [simv] Error 127
Makefile:581: recipe for target 'simv' failed
make: Leaving directory '/home/chifred/NVDLA/nvdlav1/hw/verif/sim'
logfile: outdir/build.log
==============================================
Filehandle GEN1 opened only for input at /usr/local/share/perl/5.22.1/IO/Tee.pm line 132.
==================BUILD PASS==================
Filehandle GEN1 opened only for input at /usr/local/share/perl/5.22.1/IO/Tee.pm line 132.
==============================================
Filehandle GEN1 opened only for input at /usr/local/share/perl/5.22.1/IO/Tee.pm line 132.

**Comment by nvhook** [comment] 2018-07-23 21:06
Is this resolved, @chifredhong ? 
If VCS is not installed, then yes, install it. 
If VCS is not installed, then check the path to it (log reports /home/tools/vcs/mx-2015.09-SP2-9-T0426/bin/vcs ).

**Comment by chifredhong** [comment] 2018-07-25 04:44
I used verilator to compile RTL, but 20GB RAM is needed. I don't have vcs license ，so no more progress with the hw installation

**Comment by nvhook** [comment] 2018-07-27 22:42
OK, since the problem is not something that anyone on the forum can help with, I'll close this issue.

**Closed by nvhook** 2018-07-27 22:42 UTC

**Comment by huayangshiboqi** [comment] 2019-05-13 03:00
在/hw/verif/sim/的Makefile文件里，好像需要设置vcs和verdi的软件路径啊，不然找不到这两个软件。
